### ISSUE TITLE
implements scalar reader [go]

### ISSUE THREAD

**Issue by criloz** [nebtex/hybrids#17]
- [x] implements Int8
- [x] the method should not panic if the field is not defined because is 0 in the vtable or because does not exist,  `ok` should return false, and value 0 for numbers and false for boolean
- [x] after you implement int8 please show me your implementation for doing some corrections
- [x] create a test to see that int8 is working properly
- [x] generate the other scalar accessors using go generate and int8 as template

**Comment by ljesparis** [comment]
closes #17
